
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <base href="<?= BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/estilos.css">
    <title>TPE Biblioteca</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-dark">
            <div class="container-fluid">
                <a class="nav-link" href="home"><span style="color: white">HOME</span></a>                
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="prestamos"><span style="color: white">PRÉSTAMOS</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="libros"><span style="color: white">NUESTROS LIBROS</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="usuarios"><span style="color: white">USUARIOS REGISTRADOS</span></a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <?php if (!isset($_SESSION['id_usuario'])) : ?>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="login"><span style="color: white">Iniciar sesión</span></a>
                        </li>
                        <?php else : ?>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="logout"><span style="color: white">Cerrar sesión</span></a>
                        </li>
                        <?php endif ?>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main class="container mt-3">