<?php require 'templates/header.phtml' ?>

<ul class="list-group">
    <li class="list-group-item list-group-item-dark tamañoFuente"><span class="h3">Libro: <?= $libro->titulo ?></span></li>
    <li class="list-group-item list-group-item-dark tamañoFuente"><span class="h3">Autor: <?= $libro->autor ?></span></li>
    <li class="list-group-item list-group-item-dark tamañoFuente"><span class="h3">Prestado: <?= $libro->prestado ?></span></li>
    <li class="list-group-item list-group-item-dark tamañoFuente">
        <span class="h3">Imagen:</span>
        <?php if (!empty($libro->imagen)): ?>
            <img src="<?= BASE_URL . $libro->imagen ?>" alt="Imagen del libro" width="200" height="300">
        <?php else: ?>
            No hay imagen disponible
        <?php endif; ?>
    </li>
</ul>

<a href="home/" class='btn btn-success ml-auto' type="button">Volver al inicio</a>
<a href="libros/" class='btn btn-warning ml-auto' type="button">Ver todos los libros</a>

<?php require 'templates/footer.phtml' ?>
