<?php require_once './templates/header.phtml' ?>
<h1>Libros disponibles:</h1>

<form method="post" action="agregarLibro/" class="form-control form-control-sm" enctype="multipart/form-data">
    <label class="h5">Ingrese el título</label>
    <input type="text" name="titulo" id="titulo">

    <label class="h5">Ingrese su autor</label>
    <input type="text" name="autor" id="autor">

    <label class="h5">El libro está prestado?</label>
    <input type="hidden" name="prestado" value="0">
    <input type="checkbox" name="prestado" id="prestado" value="1"
        <?php if (isset($libro) && $libro->prestado == "1") echo "checked"; ?>>

    <label class="h5">Ingrese su imagen</label>
    <input type="file" name="imagen" id="imagen">

    <button type="submit" class='btn btn-success ml-auto'>Agregar</button>
</form>

<table class="table table-dark table-striped table-hover">
    <thead>
        <th>ID</th>
        <th>Libro</th>
        <th>Autor</th>
        <th>Prestado?</th>
        <th>Imagen</th>
        <th></th>
        <th></th>
    </thead>
    <?php foreach($list as $item): ?>
    
    <tbody>
        <tr>
            <td><?= $item->id_libro ?></td>
            <td><?= $item->titulo ?></td>
            <td><?= $item->autor ?></td>
            <td><?= $item->prestado ?></td>
            <td>
                <?php if (!empty($item->imagen)): ?>
                    <img src="<?= BASE_URL . $item->imagen ?>" alt="Imagen del libro" width="100" height="150">
                <?php else: ?>
                    No hay imagen
                <?php endif; ?>
            </td>
            <td><a href="eliminarLibro/<?= $item->id_libro ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a></td>
            <td><a href="editarLibro/<?= $item->id_libro ?>" type="button" class='btn btn-success ml-auto'>Editar</a></td>
        </tr>
    </tbody>
    <?php endforeach ?>
</table>

