<?php require_once './templates/header.phtml'?>
<h1>Nuestros prestamos:</h1>
<form class="form-control form-control-sm" method="post" action="agregarPrestamo/">
    <label class="h5">Ingrese el ID del usuario</label>
        <input type="number" name="id_usuario" id="id_usuario">
    </select>
    <label class="h5">Ingrese el ID del libro</label>
        <input type="number" name="id_libro" id="id_libro">
    </select>
    <label class="h5">Ingrese la fecha del prestamo</label>
        <input type="date" name="fecha_prestamo" id="fecha_prestamo">
    </select>
    <button type="submit" class='btn btn-success ml-auto'>Agregar</button>
</form>
<table class="table table-dark table-striped table-hover">
    <thead>
        <th>ID Usuario</th>
        <th>ID Libro</th>
        <th>Fecha del prestamo</th>
        <th></th>
        <th></th>
    </thead>
    <?php
    foreach($list as $item):?>
    
    <tbody>
        <tr>
            <td><?= $item->id_usuario ?></td>
            <td><?= $item->id_libro ?></td>
            <td><?= $item->fecha_prestamo ?></td>
            <td><a href="eliminarPrestamo/<?= $item->id_prestamo ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a></td>
            <td><a href="editarPrestamo/<?= $item->id_prestamo ?>" type="button" class='btn btn-success ml-auto'>Editar</a></td>

        </tr>
    </tbody>
    <?php endforeach?> 
</table>  
