<?php require_once './templates/header.phtml'?>
<h1>Préstamos vigentes:</h1>

<table class="table table-dark table-striped table-hover">
    <thead>
        <th>id_usuario</th>
        <th>Título del libro</th>
        <th>Fecha del préstamo</th>
    </thead>
    <?php
    foreach($list as $item):?>
    
    <tbody>
        <tr>
            <td><?= $item->id_usuario ?></td>
            <td><?= $item->titulo_libro ?></td>
            <td><?= $item->fecha_prestamo ?></td>
        </tr>
    </tbody>
<?php endforeach?>
</table>   
<?php require_once './templates/footer.phtml'?>