<?php require_once './templates/header.phtml'?>

<ul>
        <li>Usuario: <?= $prestamo->id_usuario ?></li>
        <li>Titulo libro: <?= $prestamo->titulo_libro ?></li>
        <li>Fecha: <?= $prestamo->fecha_prestamo?></li>
        
    </ul>
    <form method="post" action="actualizarPrestamo/<?=$prestamoId?>">
    <label>Ingrese su usuario</label>
        <input type="text" name="nombre" id="nombre">
    </select>
    <label>Ingrese el titulo del libro</label>
        <input type="text" name="titulo" id="titulo">
    </select>
    <label>Ingrese la fecha del prestamo</label>
        <input type="date" name="fecha" id="fecha">
    </select>
    <button type="submit">Actualizar</button>
</form>


<?php require_once './templates/footer.phtml'?>