<?php require_once './templates/header.phtml'?>
<h1>Préstamos vigentes:</h1>

<table class="table table-dark table-striped table-hover">
    <thead>
        <th>ID Usuario</th>
        <th>ID Libro</th>
        <th>Fecha del préstamo</th>
        <th></th>
    </thead>
    <?php
    foreach($list as $item):?>
    
    <tbody>
        <tr>
            <td><?= $item->id_usuario ?></td>
            <td><?= $item->id_libro ?></td>
            <td><?= $item->fecha_prestamo ?></td>

            <td><a href="prestamo/<?= $item->id_prestamo ?>" type="button" class='btn btn-success ml-auto'>Ver</a></td>
        </tr>
    </tbody>
<?php endforeach?>
</table>   

