<?php require 'templates/header.phtml'; ?>
<form method="post" action="actualizarPrestamo/<?=$prestamoId?>">
    <label>Ingrese el ID del usuario</label>
    <input type="number" value="<?= $prestamo->id_usuario ?>" name="id_usuario" id="id_usuario">
    
    <label>Ingrese el ID del libro</label>
    <input type="number" value="<?= $prestamo->id_libro ?>" name="id_libro" id="id_libro">
    
    <label>Ingrese la fecha del préstamo</label>
    <input type="date" value="<?= $prestamo->fecha_prestamo ?>" name="fecha_prestamo" id="fecha_prestamo">
    
    <button type="submit">Actualizar</button>
</form>
<?php require 'templates/footer.phtml'; ?>