<?php require 'templates/header.phtml'; ?>

<div class="mt-5 w-25 mx-auto">
    <form method="POST" action="http://localhost/Biblioteca/router.php?action=register">
        <div class="form-group">
            <label for="usuario">Email</label>
            <input type="text" class="form-control" id="usuario" name="usuario" aria-describedby="userHelp">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password">
        </div>

       
        <button type="submit" class="btn btn-primary mt-3">Entrar</button>

    </form>         
</div>

<?php require './templates/footer.phtml'; ?>