<?php require_once './templates/header.phtml'?>
<h1>Usuarios registrados:</h1>
<form method="post" action="agregarUsuario/" class="form-control form-control-sm">
    <label class="h5">Ingrese el usuario</label>
    <input type="text" name="usuario" id="usuario">

    <label class="h5">Es admin?</label>
    <input type="hidden" name="admin" value="0">
    <input type="checkbox" name="admin" id="admin" value="1"
        <?php if (isset($admin) && $admin->admin == "1") echo "checked"; ?>>

    <button type="submit" class='btn btn-success ml-auto'>Agregar</button>
</form>
<table class="table table-dark table-striped table-hover">
    <thead>
        <th>ID</th>
        <th>Usuario</th>
        <th>Es admin?</th>
        <th></th>
        <th></th>
    </thead>
    <?php
    foreach($list as $item):?>
    
    <tbody>
        <tr>
            <td><?= $item->id_usuario ?></td>
            <td><?= $item->usuario ?></td>
            <td><?= $item->admin ?></td>
            <td><a href="eliminarUsuario/<?= $item->id_usuario ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a></td>
            <td><a href="editarUsuario/<?= $item->id_usuario ?>" type="button" class='btn btn-success ml-auto'>Editar</a></td>
        </tr>
    </tbody>
<?php endforeach?>
