<?php require 'templates/header.phtml' ?>

    <ul class="list-group">
        <li class="list-group-item list-group-item-dark tamañoFuente"><span class="h3">ID: <?= $usuario->id_usuario ?></span></li>
        <li class="list-group-item list-group-item-dark tamañoFuente"><span class="h3">Usuario: <?= $usuario->usuario ?></span></li>
        <li class="list-group-item list-group-item-dark tamañoFuente"><span class="h3">Admin: <?= $usuario->admin ?></span></li>
        
    </ul>
    <a href="home/" class='btn btn-success ml-auto'type="button">Volver al inicio</a>
    <a href="usuarios/" class='btn btn-warning ml-auto' type="button">Ver todos los usuarios</a>
<?php require 'templates/footer.phtml' ?>